name 'p'
version '2.0'
source 'git://github.com/phppro/puppet-bootstrap.git'
author 'phppro'
license 'Apache 2.0'
summary 'Puppet module for bootstraping'
description 'Module for Bootstraping'
project_page 'https://github.com/phppro/puppet-bootstrap'
